version: "3.9"

services:
  db:
    image: postgres:14.5
    environment:
      - POSTGRES_DB=geoleague
      - POSTGRES_USER=geouser
      - POSTGRES_PASSWORD=geoPASS123
    ports:
      - "5432:5432"
  #    expose:
  #      - "5432"

  test-db:
    image: postgres:14.5
    environment:
      - POSTGRES_DB=geoleague
      - POSTGRES_USER=geouser
      - POSTGRES_PASSWORD=geoPASS123
    ports:
      - "5433:5432"
    #    expose:
    #      - "5432"

  backend:
    image: geoleague_backend
    environment:
      - DB_PORT=5432
      - TEST_DB_PORT=5432
    depends_on:
      - db
    ports:
      - "8000:8000"

  frontend:
    image: geoleague_frontend
    ports:
      - "80:80"

