version: "3.9"

services:
  db:
    build: ./database
    ports:
      - "5432:5432"

  test-db:
    build: ./database
    ports:
      - "5433:5432"

  backend:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DB_URL=postgresql://geouser:geoPASS123@db:5432/geoleague
      - TEST_DB_URL=postgresql://geouser:geoPASS123@test-db:5433/geoleague
      - DB_NAME=geoleague
      - DB_USER=geouser
      - DB_PASSWORD=geoPASS123
