version: "3.9"

services:
  db:
    build: ./database
    expose:
      - "5432"

  test-db:
    build: ./database
    expose:
      - "5432"

  backend:
    image: geoleague_backend
    environment:
      - DB_PORT=5432
      - TEST_DB_PORT=5432
    depends_on:
      - db
    ports:
      - "8000:8000"

  frontend:
    image: geoleague_frontend
    ports:
      - "80:80"

