"""Adds round_number in round

Revision ID: 313149376c7a
Revises: 8274560a8de7
Create Date: 2022-09-19 20:20:19.049315

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '313149376c7a'
down_revision = '8274560a8de7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('round', sa.Column('round_number', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('round', 'round_number')
    # ### end Alembic commands ###
