"""Adds mutual relationships

Revision ID: 7a61d6b8ea03
Revises: e29c476b4926
Create Date: 2022-09-17 12:54:04.582154

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a61d6b8ea03'
down_revision = 'e29c476b4926'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
