"""Adds round_limit

Revision ID: e29c476b4926
Revises: 702f3047070f
Create Date: 2022-09-17 12:32:16.966418

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e29c476b4926'
down_revision = '702f3047070f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game', sa.Column('round_limit', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('game', 'round_limit')
    # ### end Alembic commands ###
