version: "3.9"

services:
  db:
    image: postgres:14.5
    environment:
      - POSTGRES_DB=geoleague
      - POSTGRES_USER=geouser
      - POSTGRES_PASSWORD=geoPASS123
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data

  backend:
    image: yolobreaker/geoleague_backend
    environment:
      - DB_PORT=5432
      - TEST_DB_PORT=5432
    depends_on:
      - db
    restart: unless-stopped
    ports:
      - "8000:8000"

  frontend:
    image: yolobreaker/geoleague_frontend
    ports:
      - "80:80"
