version: "3.9"

services:
  db:
    image: postgres:14.5
    environment:
      - POSTGRES_DB=geoleague
      - POSTGRES_USER=geouser
      - POSTGRES_PASSWORD=geoPASS123
    volumes:
      - postgres-data:/var/lib/postgresql/data
    expose:
      - "5432"

  backend:
    image: yolobreaker/geoleague_backend
    environment:
      - DB_PORT=5432
      - TEST_DB_PORT=5432
    depends_on:
      - db
    ports:
      - "8000:8000"

  frontend:
    image: yolobreaker/geoleague_frontend
    ports:
      - "80:80"
volumes:
  postgres-data:
