"""simplify_model

Revision ID: 18fb0b4dd400
Revises: a961f851b7d3
Create Date: 2024-09-09 21:42:12.711243

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18fb0b4dd400'
down_revision = 'a961f851b7d3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('game', 'time_limit')
    op.drop_column('game', 'round_count')
    op.drop_column('game', 'map')
    op.drop_column('score', 'meta')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('score', sa.Column('meta', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('game', sa.Column('map', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('game', sa.Column('round_count', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('game', sa.Column('time_limit', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
