"""Changes id of game to str

Revision ID: 8274560a8de7
Revises: 7a61d6b8ea03
Create Date: 2022-09-18 23:13:20.701926

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8274560a8de7'
down_revision = '7a61d6b8ea03'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('game', 'round_limit')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game', sa.Column('round_limit', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
